import * as path from 'node:path';
import * as fs from 'node:fs';
import * as crypto from 'node:crypto';
import {
  Stack,
  StackProps,
  RemovalPolicy,
  Duration,
  CfnOutput,
} from 'aws-cdk-lib';
import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as s3deploy from 'aws-cdk-lib/aws-s3-deployment';
import * as cloudfront from 'aws-cdk-lib/aws-cloudfront';
import * as origins from 'aws-cdk-lib/aws-cloudfront-origins';
import * as apigw from 'aws-cdk-lib/aws-apigatewayv2';
import * as integrations from 'aws-cdk-lib/aws-apigatewayv2-integrations';
import * as secretsmanager from 'aws-cdk-lib/aws-secretsmanager';
import * as acm from 'aws-cdk-lib/aws-certificatemanager';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as scheduler from 'aws-cdk-lib/aws-scheduler';
import * as ses from 'aws-cdk-lib/aws-ses';
import { Construct } from 'constructs';

const ROOT = path.join(__dirname, '..', '..');

/**
 * The hash of the theme script inlined in index.html, so the policy can name that
 * one script instead of allowing every inline script on the page.
 *
 * Read from the built file rather than written down here: a hash copied by hand
 * goes stale the first time the script is edited, and the failure is a page that
 * silently stops setting its theme.
 */
function inlineScriptHash(): string {
  const html = fs.readFileSync(path.join(ROOT, 'web', 'dist', 'index.html'), 'utf8');
  const match = html.match(/<script>([\s\S]*?)<\/script>/);
  if (!match) {
    throw new Error('No inline script found in web/dist/index.html; the CSP hash would be wrong');
  }
  return crypto.createHash('sha256').update(match[1], 'utf8').digest('base64');
}

// The domain the app used to live at. It keeps its own certificate and
// distribution, and now serves nothing but a redirect.
const LEGACY_DOMAIN = process.env.SITE_DOMAIN ?? 'budget.ganhammar.se';
// Nothing reads replies to a reminder, and implying otherwise is worse than
// saying so.
const FROM_ADDRESS = process.env.FROM_ADDRESS ?? 'no-reply@pnkt.app';
/** Days of the month the income reminder goes out, in Swedish local time. */
const REMINDER_DAYS = [22, 25, 27];

// The VAPID key pair identifies this application server to every push service. It
// was generated once and the private half put in Secrets Manager by hand: rotating
// it invalidates every existing subscription, so it must not be regenerated by a
// deploy. The public half is not a secret; browsers need it to subscribe.
const VAPID_SECRET_ARN =
  process.env.VAPID_SECRET_ARN ??
  'arn:aws:secretsmanager:eu-north-1:519157272275:secret:budget/vapid-private-key-oG6Tgq';
const VAPID_PUBLIC_KEY =
  process.env.VAPID_PUBLIC_KEY ??
  'BP74h99k-HOU_XmsZbw9LznA0pIAJLHVdNmN6p8rR--iHsetMcOV8WeZTp8CbuwmfeJooA7TsXtSjZ3jyC-wCwA';

// CloudFront only accepts certificates from us-east-1 regardless of stack region.
// DNS lives in Cloudflare, so this was requested and validated by hand rather than
// created by CDK, and is imported by ARN.
const CERTIFICATE_ARN =
  process.env.CERTIFICATE_ARN ??
  'arn:aws:acm:us-east-1:519157272275:certificate/aada0efe-f233-42da-8326-54c5135b7527';

export interface BudgetStackProps extends StackProps {
  /** Apex domain the app is moving to; a public hosted zone in this account. */
  appDomain: string;
  /** Covers the apex and www, from the us-east-1 certificate stack. */
  appCertificateArn: string;
}

export class BudgetStack extends Stack {
  constructor(scope: Construct, id: string, props: BudgetStackProps) {
    super(scope, id, props);

    const { appDomain, appCertificateArn } = props;

    /* ---------- Data ---------- */

    const table = new dynamodb.TableV2(this, 'Table', {
      partitionKey: { name: 'pk', type: dynamodb.AttributeType.STRING },
      sortKey: { name: 'sk', type: dynamodb.AttributeType.STRING },
      billing: dynamodb.Billing.onDemand(),
      pointInTimeRecoverySpecification: { pointInTimeRecoveryEnabled: true },
      // Household finances: losing the table to a stack delete would be unrecoverable.
      removalPolicy: RemovalPolicy.RETAIN,
    });

    /* ---------- API ---------- */

    // Signs the session cookie. Generated once and never in the template, so
    // rotating it is a matter of changing the secret rather than redeploying code.
    const sessionSecret = new secretsmanager.Secret(this, 'SessionSecret', {
      description: 'HMAC key for Budget session cookies',
      generateSecretString: {
        passwordLength: 64,
        excludePunctuation: true,
      },
      removalPolicy: RemovalPolicy.RETAIN,
    });

    const vapidSecret = secretsmanager.Secret.fromSecretCompleteArn(
      this,
      'VapidSecret',
      VAPID_SECRET_ARN,
    );

    const googleClientId = process.env.GOOGLE_CLIENT_ID;
    if (!googleClientId) {
      throw new Error('GOOGLE_CLIENT_ID must be set to synthesize the API');
    }

    const api = new lambda.Function(this, 'Api', {
      // Custom runtime, zip payload. The executable is named `bootstrap`.
      runtime: lambda.Runtime.PROVIDED_AL2023,
      architecture: lambda.Architecture.ARM_64,
      handler: 'bootstrap',
      code: lambda.Code.fromAsset(path.join(ROOT, 'api', 'publish')),
      memorySize: 512,
      timeout: Duration.seconds(20),
      environment: {
        TABLE_NAME: table.tableName,
        GOOGLE_CLIENT_ID: googleClientId,
        SESSION_SECRET_ARN: sessionSecret.secretArn,
        FROM_ADDRESS: FROM_ADDRESS,
        APP_URL: `https://${appDomain}`,
        VAPID_SECRET_ARN: vapidSecret.secretArn,
        VAPID_PUBLIC_KEY: VAPID_PUBLIC_KEY,
      },
    });

    table.grantReadWriteData(api);
    sessionSecret.grantRead(api);
    vapidSecret.grantRead(api);

    /* ---------- Monthly income reminders ---------- */

    const reminders = new lambda.Function(this, 'Reminders', {
      runtime: lambda.Runtime.PROVIDED_AL2023,
      architecture: lambda.Architecture.ARM_64,
      handler: 'bootstrap',
      code: lambda.Code.fromAsset(path.join(ROOT, 'api', 'publish-reminders')),
      memorySize: 512,
      timeout: Duration.minutes(2),
      environment: {
        TABLE_NAME: table.tableName,
        FROM_ADDRESS: FROM_ADDRESS,
        APP_URL: `https://${appDomain}`,
        VAPID_SECRET_ARN: vapidSecret.secretArn,
        VAPID_PUBLIC_KEY: VAPID_PUBLIC_KEY,
      },
    });

    // Writes as well as reads: a subscription the push service reports as gone is
    // deleted during the run rather than retried every month.
    table.grantReadWriteData(reminders);
    vapidSecret.grantRead(reminders);

    // Scoped to the one verified identity rather than ses:SendEmail on *.
    const sendEmail = new iam.PolicyStatement({
      actions: ['ses:SendEmail'],
      resources: [
        `arn:aws:ses:${this.region}:${this.account}:identity/${FROM_ADDRESS.split('@')[1]}`,
      ],
    });
    api.addToRolePolicy(sendEmail);
    reminders.addToRolePolicy(sendEmail);

    const schedulerRole = new iam.Role(this, 'SchedulerRole', {
      assumedBy: new iam.ServicePrincipal('scheduler.amazonaws.com'),
    });
    reminders.grantInvoke(schedulerRole);

    // On the 1st, so there is a month to get an offer before a loan's fixed term
    // rolls over on its own.
    new scheduler.CfnSchedule(this, 'ResetNotice', {
      flexibleTimeWindow: { mode: 'OFF' },
      scheduleExpression: 'cron(0 8 1 * ? *)',
      scheduleExpressionTimezone: 'Europe/Stockholm',
      target: {
        arn: reminders.functionArn,
        roleArn: schedulerRole.roleArn,
        input: JSON.stringify({ kind: 'reset' }),
        retryPolicy: { maximumRetryAttempts: 2 },
      },
    });

    REMINDER_DAYS.forEach((day, index) => {
      new scheduler.CfnSchedule(this, `Reminder${day}`, {
        flexibleTimeWindow: { mode: 'OFF' },
        scheduleExpression: `cron(0 8 ${day} * ? *)`,
        // EventBridge Rules cannot do this; only Scheduler honours a timezone, and
        // without it "the 22nd" drifts an hour twice a year.
        scheduleExpressionTimezone: 'Europe/Stockholm',
        target: {
          arn: reminders.functionArn,
          roleArn: schedulerRole.roleArn,
          input: JSON.stringify({ final: index === REMINDER_DAYS.length - 1 }),
          retryPolicy: { maximumRetryAttempts: 2 },
        },
      });
    });

    // A Lambda function URL behind CloudFront OAC looks tempting, but OAC signs the
    // request without the body, so every POST/PUT fails SigV4 validation with a 403.
    // HTTP API has no such problem and costs about a dollar per million requests.
    const httpApi = new apigw.HttpApi(this, 'HttpApi', {
      defaultIntegration: new integrations.HttpLambdaIntegration('ApiIntegration', api),
    });

    // Blunt protection for everything behind it. A household generates a handful of
    // requests a minute; anything near these numbers is not someone keeping a budget.
    (httpApi.defaultStage!.node.defaultChild as apigw.CfnStage).defaultRouteSettings = {
      throttlingRateLimit: 25,
      throttlingBurstLimit: 50,
    };

    const apiDomain = `${httpApi.apiId}.execute-api.${this.region}.${this.urlSuffix}`;

    /* ---------- Web ---------- */

    /*
     * Everything comes from this origin except Google's sign-in, which needs its
     * script, the frame it renders the button in, and the requests it makes to
     * complete a sign-in. Styles allow inline because React sets a few through the
     * style attribute.
     */
    const csp = [
      "default-src 'self'",
      `script-src 'self' 'sha256-${inlineScriptHash()}' https://accounts.google.com`,
      // Google's script pulls its own stylesheet into this document, not just into
      // the frame it renders. Inline is for the handful React sets as attributes.
      "style-src 'self' 'unsafe-inline' https://accounts.google.com",
      "img-src 'self' data: https://*.gstatic.com https://*.googleusercontent.com",
      "connect-src 'self' https://accounts.google.com",
      "frame-src https://accounts.google.com",
      "font-src 'self'",
      "manifest-src 'self'",
      "worker-src 'self'",
      "object-src 'none'",
      "base-uri 'self'",
      "form-action 'self'",
      "frame-ancestors 'none'",
    ].join('; ');

    const securityHeaders = new cloudfront.ResponseHeadersPolicy(this, 'SecurityHeaders', {
      securityHeadersBehavior: {
        contentSecurityPolicy: { contentSecurityPolicy: csp, override: true },
        strictTransportSecurity: {
          accessControlMaxAge: Duration.days(365),
          includeSubdomains: true,
          override: true,
        },
        contentTypeOptions: { override: true },
        frameOptions: { frameOption: cloudfront.HeadersFrameOption.DENY, override: true },
        referrerPolicy: {
          referrerPolicy: cloudfront.HeadersReferrerPolicy.STRICT_ORIGIN_WHEN_CROSS_ORIGIN,
          override: true,
        },
      },
    });

    const site = new s3.Bucket(this, 'Site', {
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      encryption: s3.BucketEncryption.S3_MANAGED,
      enforceSSL: true,
      removalPolicy: RemovalPolicy.DESTROY,
      autoDeleteObjects: true,
    });

    // Everything that reaches the old domain is sent to the new one, path intact.
    // Bookmarks and home-screen shortcuts keep working; what they open is pnkt.app.
    const redirectToApp = new cloudfront.Function(this, 'RedirectToApp', {
      runtime: cloudfront.FunctionRuntime.JS_2_0,
      code: cloudfront.FunctionCode.fromInline(`
function handler(event) {
  var request = event.request;
  var query = '';
  for (var key in request.querystring) {
    query += (query ? '&' : '?') + key + '=' + request.querystring[key].value;
  }
  return {
    statusCode: 301,
    statusDescription: 'Moved Permanently',
    headers: { location: { value: 'https://${appDomain}' + request.uri + query } },
  };
}`),
    });

    const distribution = new cloudfront.Distribution(this, 'Distribution', {
      domainNames: [LEGACY_DOMAIN],
      certificate: acm.Certificate.fromCertificateArn(this, 'Certificate', CERTIFICATE_ARN),
      defaultBehavior: {
        // An origin is required even though the function answers every request
        // before one is made.
        origin: origins.S3BucketOrigin.withOriginAccessControl(site),
        viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
        cachePolicy: cloudfront.CachePolicy.CACHING_DISABLED,
        responseHeadersPolicy: securityHeaders,
        functionAssociations: [
          { function: redirectToApp, eventType: cloudfront.FunctionEventType.VIEWER_REQUEST },
        ],
      },
    });

    /* ---------- pnkt.app ---------- */

    // A second distribution rather than new aliases on the first: a distribution
    // carries one certificate, and the old domain's DNS lives in Cloudflare so its
    // certificate cannot be reissued from here. Both serve the app while the move
    // is in progress; the old one is retired once sign-in works on the new domain.
    //
    // DNS for this domain is at Cloudflare too, because the registrar is Cloudflare
    // and it does not offer custom nameservers. So there are no records here: the
    // apex and www CNAMEs, the certificate validation and the DKIM records below
    // are all added by hand there.

    // One name for one thing. www exists because people type it, not as an address
    // the app answers to.
    const redirectToApex = new cloudfront.Function(this, 'RedirectToApex', {
      runtime: cloudfront.FunctionRuntime.JS_2_0,
      code: cloudfront.FunctionCode.fromInline(`
function handler(event) {
  var request = event.request;
  if (request.headers.host.value !== 'www.${appDomain}') return request;

  // The app routes on the hash and uses no query strings, but carrying them
  // costs four lines and means the redirect is never the thing that lost one.
  var query = '';
  for (var key in request.querystring) {
    query += (query ? '&' : '?') + key + '=' + request.querystring[key].value;
  }

  return {
    statusCode: 301,
    statusDescription: 'Moved Permanently',
    headers: { location: { value: 'https://${appDomain}' + request.uri + query } },
  };
}`),
    });

    const appDistribution = new cloudfront.Distribution(this, 'AppDistribution', {
      domainNames: [appDomain, `www.${appDomain}`],
      certificate: acm.Certificate.fromCertificateArn(this, 'AppCertificate', appCertificateArn),
      defaultRootObject: 'index.html',
      defaultBehavior: {
        origin: origins.S3BucketOrigin.withOriginAccessControl(site),
        viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
        cachePolicy: cloudfront.CachePolicy.CACHING_OPTIMIZED,
        responseHeadersPolicy: securityHeaders,
        functionAssociations: [
          {
            function: redirectToApex,
            eventType: cloudfront.FunctionEventType.VIEWER_REQUEST,
          },
        ],
      },
      additionalBehaviors: {
        'api/*': {
          origin: new origins.HttpOrigin(apiDomain),
          viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
          allowedMethods: cloudfront.AllowedMethods.ALLOW_ALL,
          cachePolicy: cloudfront.CachePolicy.CACHING_DISABLED,
          originRequestPolicy: cloudfront.OriginRequestPolicy.ALL_VIEWER_EXCEPT_HOST_HEADER,
        },
      },
      // No SPA error-page fallback on purpose. The app routes on the hash, so there
      // are no deep paths to rewrite, and a distribution-wide rule would silently
      // turn genuine API 403s and 404s into a 200 page of HTML.
    });

    // The tokens are outputs rather than records: nothing here can write to a zone
    // Cloudflare serves. Verification follows once they are added there, which is
    // why FROM_ADDRESS does not move in the same deploy that creates this.
    const mail = new ses.EmailIdentity(this, 'AppMailIdentity', {
      identity: ses.Identity.domain(appDomain),
    });

    mail.dkimRecords.forEach((record, index) => {
      new CfnOutput(this, `MailDkim${index + 1}`, {
        value: `${record.name} CNAME ${record.value}`,
      });
    });

    const assets = new s3deploy.BucketDeployment(this, 'DeploySite', {
      sources: [s3deploy.Source.asset(path.join(ROOT, 'web', 'dist'))],
      destinationBucket: site,
      exclude: ['index.html'],
      // Nothing is pruned: a browser still holding an older index.html asks for the
      // bundles that one named, and deleting them turns a stale tab into a blank
      // page rather than a page one refresh behind.
      prune: false,
      cacheControl: [
        s3deploy.CacheControl.setPublic(),
        s3deploy.CacheControl.maxAge(Duration.days(365)),
        s3deploy.CacheControl.immutable(),
      ],
      distribution: appDistribution,
      distributionPaths: ['/*'],
    });

    const entry = new s3deploy.BucketDeployment(this, 'DeployIndex', {
      sources: [s3deploy.Source.asset(path.join(ROOT, 'web', 'dist'), { exclude: ['assets/*'] })],
      destinationBucket: site,
      prune: false,
      cacheControl: [s3deploy.CacheControl.noCache()],
      distribution: appDistribution,
      distributionPaths: ['/index.html'],
    });

    // The page that names the bundles is written after the bundles exist.
    entry.node.addDependency(assets);

    new CfnOutput(this, 'SiteUrl', { value: `https://${distribution.distributionDomainName}` });
    new CfnOutput(this, 'AppUrl', { value: `https://${appDomain}` });
    new CfnOutput(this, 'TableName', { value: table.tableName });
    new CfnOutput(this, 'ApiFunctionName', { value: api.functionName });
    new CfnOutput(this, 'RemindersFunctionName', { value: reminders.functionName });
  }
}
