import * as path from 'node:path';
import {
  Stack,
  StackProps,
  RemovalPolicy,
  Duration,
  CfnOutput,
} from 'aws-cdk-lib';
import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as s3deploy from 'aws-cdk-lib/aws-s3-deployment';
import * as cloudfront from 'aws-cdk-lib/aws-cloudfront';
import * as origins from 'aws-cdk-lib/aws-cloudfront-origins';
import * as apigw from 'aws-cdk-lib/aws-apigatewayv2';
import * as integrations from 'aws-cdk-lib/aws-apigatewayv2-integrations';
import * as secretsmanager from 'aws-cdk-lib/aws-secretsmanager';
import * as acm from 'aws-cdk-lib/aws-certificatemanager';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as scheduler from 'aws-cdk-lib/aws-scheduler';
import * as route53 from 'aws-cdk-lib/aws-route53';
import * as targets from 'aws-cdk-lib/aws-route53-targets';
import * as ses from 'aws-cdk-lib/aws-ses';
import { Construct } from 'constructs';

const ROOT = path.join(__dirname, '..', '..');

const SITE_DOMAIN = process.env.SITE_DOMAIN ?? 'budget.ganhammar.se';
const FROM_ADDRESS = process.env.FROM_ADDRESS ?? 'budget@ganhammar.se';
/** Days of the month the income reminder goes out, in Swedish local time. */
const REMINDER_DAYS = [22, 25, 27];

// The VAPID key pair identifies this application server to every push service. It
// was generated once and the private half put in Secrets Manager by hand: rotating
// it invalidates every existing subscription, so it must not be regenerated by a
// deploy. The public half is not a secret; browsers need it to subscribe.
const VAPID_SECRET_ARN =
  process.env.VAPID_SECRET_ARN ??
  'arn:aws:secretsmanager:eu-north-1:519157272275:secret:budget/vapid-private-key-oG6Tgq';
const VAPID_PUBLIC_KEY =
  process.env.VAPID_PUBLIC_KEY ??
  'BP74h99k-HOU_XmsZbw9LznA0pIAJLHVdNmN6p8rR--iHsetMcOV8WeZTp8CbuwmfeJooA7TsXtSjZ3jyC-wCwA';

// CloudFront only accepts certificates from us-east-1 regardless of stack region.
// DNS lives in Cloudflare, so this was requested and validated by hand rather than
// created by CDK, and is imported by ARN.
const CERTIFICATE_ARN =
  process.env.CERTIFICATE_ARN ??
  'arn:aws:acm:us-east-1:519157272275:certificate/aada0efe-f233-42da-8326-54c5135b7527';

export interface BudgetStackProps extends StackProps {
  /** Apex domain the app is moving to; a public hosted zone in this account. */
  appDomain: string;
  /** Covers the apex and www, from the us-east-1 certificate stack. */
  appCertificateArn: string;
}

export class BudgetStack extends Stack {
  constructor(scope: Construct, id: string, props: BudgetStackProps) {
    super(scope, id, props);

    const { appDomain, appCertificateArn } = props;

    /* ---------- Data ---------- */

    const table = new dynamodb.TableV2(this, 'Table', {
      partitionKey: { name: 'pk', type: dynamodb.AttributeType.STRING },
      sortKey: { name: 'sk', type: dynamodb.AttributeType.STRING },
      billing: dynamodb.Billing.onDemand(),
      pointInTimeRecoverySpecification: { pointInTimeRecoveryEnabled: true },
      // Household finances: losing the table to a stack delete would be unrecoverable.
      removalPolicy: RemovalPolicy.RETAIN,
    });

    /* ---------- API ---------- */

    // Signs the session cookie. Generated once and never in the template, so
    // rotating it is a matter of changing the secret rather than redeploying code.
    const sessionSecret = new secretsmanager.Secret(this, 'SessionSecret', {
      description: 'HMAC key for Budget session cookies',
      generateSecretString: {
        passwordLength: 64,
        excludePunctuation: true,
      },
      removalPolicy: RemovalPolicy.RETAIN,
    });

    const vapidSecret = secretsmanager.Secret.fromSecretCompleteArn(
      this,
      'VapidSecret',
      VAPID_SECRET_ARN,
    );

    const googleClientId = process.env.GOOGLE_CLIENT_ID;
    if (!googleClientId) {
      throw new Error('GOOGLE_CLIENT_ID must be set to synthesize the API');
    }

    const api = new lambda.Function(this, 'Api', {
      // Custom runtime, zip payload. The executable is named `bootstrap`.
      runtime: lambda.Runtime.PROVIDED_AL2023,
      architecture: lambda.Architecture.ARM_64,
      handler: 'bootstrap',
      code: lambda.Code.fromAsset(path.join(ROOT, 'api', 'publish')),
      memorySize: 512,
      timeout: Duration.seconds(20),
      environment: {
        TABLE_NAME: table.tableName,
        GOOGLE_CLIENT_ID: googleClientId,
        SESSION_SECRET_ARN: sessionSecret.secretArn,
        FROM_ADDRESS: FROM_ADDRESS,
        APP_URL: `https://${SITE_DOMAIN}`,
        VAPID_SECRET_ARN: vapidSecret.secretArn,
        VAPID_PUBLIC_KEY: VAPID_PUBLIC_KEY,
      },
    });

    table.grantReadWriteData(api);
    sessionSecret.grantRead(api);
    vapidSecret.grantRead(api);

    /* ---------- Monthly income reminders ---------- */

    const reminders = new lambda.Function(this, 'Reminders', {
      runtime: lambda.Runtime.PROVIDED_AL2023,
      architecture: lambda.Architecture.ARM_64,
      handler: 'bootstrap',
      code: lambda.Code.fromAsset(path.join(ROOT, 'api', 'publish-reminders')),
      memorySize: 512,
      timeout: Duration.minutes(2),
      environment: {
        TABLE_NAME: table.tableName,
        FROM_ADDRESS: FROM_ADDRESS,
        APP_URL: `https://${SITE_DOMAIN}`,
        VAPID_SECRET_ARN: vapidSecret.secretArn,
        VAPID_PUBLIC_KEY: VAPID_PUBLIC_KEY,
      },
    });

    // Writes as well as reads: a subscription the push service reports as gone is
    // deleted during the run rather than retried every month.
    table.grantReadWriteData(reminders);
    vapidSecret.grantRead(reminders);

    // Scoped to the one verified identity rather than ses:SendEmail on *.
    const sendEmail = new iam.PolicyStatement({
      actions: ['ses:SendEmail'],
      resources: [
        `arn:aws:ses:${this.region}:${this.account}:identity/${FROM_ADDRESS.split('@')[1]}`,
      ],
    });
    api.addToRolePolicy(sendEmail);
    reminders.addToRolePolicy(sendEmail);

    const schedulerRole = new iam.Role(this, 'SchedulerRole', {
      assumedBy: new iam.ServicePrincipal('scheduler.amazonaws.com'),
    });
    reminders.grantInvoke(schedulerRole);

    // On the 1st, so there is a month to get an offer before a loan's fixed term
    // rolls over on its own.
    new scheduler.CfnSchedule(this, 'ResetNotice', {
      flexibleTimeWindow: { mode: 'OFF' },
      scheduleExpression: 'cron(0 8 1 * ? *)',
      scheduleExpressionTimezone: 'Europe/Stockholm',
      target: {
        arn: reminders.functionArn,
        roleArn: schedulerRole.roleArn,
        input: JSON.stringify({ kind: 'reset' }),
        retryPolicy: { maximumRetryAttempts: 2 },
      },
    });

    REMINDER_DAYS.forEach((day, index) => {
      new scheduler.CfnSchedule(this, `Reminder${day}`, {
        flexibleTimeWindow: { mode: 'OFF' },
        scheduleExpression: `cron(0 8 ${day} * ? *)`,
        // EventBridge Rules cannot do this; only Scheduler honours a timezone, and
        // without it "the 22nd" drifts an hour twice a year.
        scheduleExpressionTimezone: 'Europe/Stockholm',
        target: {
          arn: reminders.functionArn,
          roleArn: schedulerRole.roleArn,
          input: JSON.stringify({ final: index === REMINDER_DAYS.length - 1 }),
          retryPolicy: { maximumRetryAttempts: 2 },
        },
      });
    });

    // A Lambda function URL behind CloudFront OAC looks tempting, but OAC signs the
    // request without the body, so every POST/PUT fails SigV4 validation with a 403.
    // HTTP API has no such problem and costs about a dollar per million requests.
    const httpApi = new apigw.HttpApi(this, 'HttpApi', {
      defaultIntegration: new integrations.HttpLambdaIntegration('ApiIntegration', api),
    });

    const apiDomain = `${httpApi.apiId}.execute-api.${this.region}.${this.urlSuffix}`;

    /* ---------- Web ---------- */

    const site = new s3.Bucket(this, 'Site', {
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      encryption: s3.BucketEncryption.S3_MANAGED,
      enforceSSL: true,
      removalPolicy: RemovalPolicy.DESTROY,
      autoDeleteObjects: true,
    });

    const distribution = new cloudfront.Distribution(this, 'Distribution', {
      domainNames: [SITE_DOMAIN],
      certificate: acm.Certificate.fromCertificateArn(this, 'Certificate', CERTIFICATE_ARN),
      defaultRootObject: 'index.html',
      defaultBehavior: {
        origin: origins.S3BucketOrigin.withOriginAccessControl(site),
        viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
        cachePolicy: cloudfront.CachePolicy.CACHING_OPTIMIZED,
      },
      additionalBehaviors: {
        // Same origin as the app, so the session cookie needs no CORS or SameSite=None.
        'api/*': {
          origin: new origins.HttpOrigin(apiDomain),
          viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
          allowedMethods: cloudfront.AllowedMethods.ALLOW_ALL,
          cachePolicy: cloudfront.CachePolicy.CACHING_DISABLED,
          originRequestPolicy: cloudfront.OriginRequestPolicy.ALL_VIEWER_EXCEPT_HOST_HEADER,
        },
      },
      // No SPA error-page fallback on purpose. The app routes on the hash, so there
      // are no deep paths to rewrite, and a distribution-wide rule would silently
      // turn genuine API 403s and 404s into a 200 page of HTML.
    });

    /* ---------- pnkt.app ---------- */

    // A second distribution rather than new aliases on the first: a distribution
    // carries one certificate, and the old domain's DNS lives in Cloudflare so its
    // certificate cannot be reissued from here. Both serve the app while the move
    // is in progress; the old one is retired once sign-in works on the new domain.
    const zone = route53.HostedZone.fromLookup(this, 'AppZone', { domainName: appDomain });

    const appDistribution = new cloudfront.Distribution(this, 'AppDistribution', {
      domainNames: [appDomain, `www.${appDomain}`],
      certificate: acm.Certificate.fromCertificateArn(this, 'AppCertificate', appCertificateArn),
      defaultRootObject: 'index.html',
      defaultBehavior: {
        origin: origins.S3BucketOrigin.withOriginAccessControl(site),
        viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
        cachePolicy: cloudfront.CachePolicy.CACHING_OPTIMIZED,
      },
      additionalBehaviors: {
        'api/*': {
          origin: new origins.HttpOrigin(apiDomain),
          viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
          allowedMethods: cloudfront.AllowedMethods.ALLOW_ALL,
          cachePolicy: cloudfront.CachePolicy.CACHING_DISABLED,
          originRequestPolicy: cloudfront.OriginRequestPolicy.ALL_VIEWER_EXCEPT_HOST_HEADER,
        },
      },
    });

    for (const [name, recordName] of [['Apex', appDomain], ['Www', `www.${appDomain}`]] as const) {
      const target = route53.RecordTarget.fromAlias(
        new targets.CloudFrontTarget(appDistribution),
      );
      new route53.ARecord(this, `AppAlias${name}`, { zone, recordName, target });
      new route53.AaaaRecord(this, `AppAliasAaaa${name}`, { zone, recordName, target });
    }

    // The zone is in the account, so the DKIM records are written by this deploy
    // rather than pasted in by hand. Verification follows a few minutes later,
    // which is why FROM_ADDRESS is not moved in the same deploy that creates this.
    new ses.EmailIdentity(this, 'AppMailIdentity', {
      identity: ses.Identity.publicHostedZone(zone),
    });

    new s3deploy.BucketDeployment(this, 'DeploySite', {
      sources: [s3deploy.Source.asset(path.join(ROOT, 'web', 'dist'))],
      destinationBucket: site,
      distribution,
      distributionPaths: ['/*'],
    });

    new CfnOutput(this, 'SiteUrl', { value: `https://${distribution.distributionDomainName}` });
    new CfnOutput(this, 'AppUrl', { value: `https://${appDomain}` });
    new CfnOutput(this, 'TableName', { value: table.tableName });
    new CfnOutput(this, 'ApiFunctionName', { value: api.functionName });
    new CfnOutput(this, 'RemindersFunctionName', { value: reminders.functionName });
  }
}
